## Tensor

In [1]:
import torch

In [3]:
x = torch.tensor(2)
print(x.shape, x.dtype)
y = torch.tensor([1.0, 3.0, 3.3])
print(y.shape, y.dtype)
z = torch.tensor([[4,5,6],[8,88, 9]])
print(z.shape, z.dtype)

torch.Size([]) torch.int64
torch.Size([3]) torch.float32
torch.Size([2, 3]) torch.int64


In [5]:
a = torch.ones(2)
b = torch.ones(2,3)
c = torch.zeros(4,5)
a, b, c

(tensor([1., 1.]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]))

In [7]:
d = torch.full((3,5), 9)
attn_mask = torch.full((4,4), float('-inf'))
d, attn_mask

(tensor([[9, 9, 9, 9, 9],
         [9, 9, 9, 9, 9],
         [9, 9, 9, 9, 9]]),
 tensor([[-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf],
         [-inf, -inf, -inf, -inf]]))

In [13]:
diagonal_mat = torch.eye(5) 
diagonal_mat

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
# torch.arange(start, end, step)

tensor_range = torch.arange(2, 21, 2)
tensor_range

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# torch.linspace(start, end, steps) This is basically means give me 5 numbers which are evenly spaced from 1-4 (both-included) 
ln_space = torch.linspace(1, 4, 5)
ln_space

tensor([1.0000, 1.7500, 2.5000, 3.2500, 4.0000])

In [ ]:
# torch.rand(shape)
rnd = torch.rand(2,3) # 0 - 1
rnd_integers = torch.randint(low=0, high=10, size=(3, 3)) # low - high in size shape
rnd_n = torch.randn(4) # -inf to inf
rnd_idx_shuffle = torch.randperm(5) # 0 - n-1 shuffle
rnd, rnd_integers, rnd_n, rnd_idx_shuffle 

(tensor([[0.5900, 0.4771, 0.8151],
         [0.7294, 0.4524, 0.9464]]),
 tensor([[5, 0, 6],
         [7, 5, 6],
         [2, 0, 0]]),
 tensor([ 0.6386, -1.0904,  1.1309,  1.3230]),
 tensor([2, 1, 3, 0, 4]))

In [ ]:
buf = torch.empty(2, 3) # uninitialized tensor with garbadge value to be written later
buf

tensor([[2.0167e-08, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4580e-19]])

#### All these above ^ hase `device=..` , `dtype=..`, `require_grad=.`

In [ ]:
# _like -> Basically 
# Every _like function does one thing: 
# copy the shape, dtype, and device of an existing tensor, then fill the new tensor using whatever rule its base function uses.
torch.zeros_like(x)   # same shape/dtype/device as x, filled with 0
torch.ones_like(x)    # same shape/dtype/device as x, filled with 1
torch.rand_like(x)    # same shape/dtype/device as x, filled uniform [0,1)
torch.randn_like(x)   # same shape/dtype/device as x, filled standard normal
torch.empty_like(x)   # same shape/dtype/device as x, uninitialized garbage
torch.full_like(x, 5) # same shape/dtype/device as x, filled with value v

In [35]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]], dtype=torch.float64, device='cuda')

# The manual way is verbose and easy to forget attributes
# zeros_manual = torch.zeros(size=x.shape, dtype=x.dtype, device=x.device)

# The _like way (clean and readable)
zeros_like = torch.zeros_like(x)
zeros_like.shape, zeros_like.dtype, zeros_like.device

(torch.Size([2, 2]), torch.float64, device(type='cuda', index=0))

In [37]:
# Boolean mask

scores = torch.tensor([0.2, 0.85, 0.4, 0.95, 0.1])
mask = scores > 0.5 
print(mask)

# Apply the mask to extract values
confident_scores = scores[mask]

print(confident_scores)

tensor([False,  True, False,  True, False])
tensor([0.8500, 0.9500])


In [38]:
xp = torch.tensor([1.0, -2.0, 3.0, -4.0])

relu_like = torch.where(xp > 0, xp, 0.0) # if xp > 0 is true then it picks xp otherwise 0.0, and it does not change the tensor shape

print(relu_like)

tensor([1., 0., 3., 0.])


In [39]:
# Using tensor index /fancy indexing 
embeddings = torch.tensor([
    [0.1, 0.1, 0.1],  
    [0.5, 0.5, 0.5],  
    [0.9, 0.9, 0.9],  
    [0.3, 0.3, 0.3],  
])

# Retrieve embeddings for word batch: [Word 2, Word 0, Word 2, Word 1]
indices = torch.tensor([2, 0, 2, 1])
batch_embeddings = embeddings[indices]

print(batch_embeddings)

tensor([[0.9000, 0.9000, 0.9000],
        [0.1000, 0.1000, 0.1000],
        [0.9000, 0.9000, 0.9000],
        [0.5000, 0.5000, 0.5000]])


In [ ]:
# Gather
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

index = torch.tensor([
    [2],
    [0]
])

out = torch.gather(x, dim=1, index=index)

print(out)

tensor([[30],
        [40]])


In [42]:
# scatter
out = torch.zeros(2, 3, dtype=torch.int64)

"""
[[0,0,0],
[0,0,0]]
"""

src = torch.tensor([
    [5, 6],
    [7, 8]
])

index = torch.tensor([
    [1, 2],
    [0, 2]
])

out.scatter_(1, index, src)

print(out)

tensor([[0, 5, 6],
        [7, 0, 8]])
