In [1]:
import torch

In [ ]:
# They Do the same thing just .view() only works for contigious tensors share the same memory 
# .reshape() works for contigious and non-contigious -> call .contigious() internally so may be copy but it is safe
a = torch.arange(12)
x = a.view(3,4)
y = a.reshape(3,4)
x,y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [13]:
# For 2 dimension swap we do .transpose(dim1, dim2) and for multiple dimention swap we use .permute()
b = torch.randint(0, 100, (2,3,4))
print(b)
print()

c = b.transpose(0,1) # so for b(2,3,4) it will be now b(3,2,4)
print(c)
print()

d = b.permute(1,2,0) # b(2,3,4) -> b(3,4,2)
print(d)

tensor([[[ 0, 46, 95, 37],
         [ 8, 76, 15, 59],
         [27, 87,  3, 20]],

        [[61, 78, 96, 15],
         [33, 90, 69, 76],
         [19, 20, 34, 19]]])

tensor([[[ 0, 46, 95, 37],
         [61, 78, 96, 15]],

        [[ 8, 76, 15, 59],
         [33, 90, 69, 76]],

        [[27, 87,  3, 20],
         [19, 20, 34, 19]]])

tensor([[[ 0, 61],
         [46, 78],
         [95, 96],
         [37, 15]],

        [[ 8, 33],
         [76, 90],
         [15, 69],
         [59, 76]],

        [[27, 19],
         [87, 20],
         [ 3, 34],
         [20, 19]]])


In [23]:
p = torch.randn(1,2,3,1) # it only removes dimension with size 1
sq = p.squeeze() # no arg = remove all size 1
q = torch.randn(1,3,1)
pq = q.squeeze(0) # pointing 1 size=1 dim to remove
sq.shape, pq.shape

(torch.Size([2, 3]), torch.Size([3, 1]))

In [ ]:
# unsqueeze() for inserting a size-1 dimension

u = torch.randn(3, 5)
b = u.unsqueeze(0)                        
c = u.unsqueeze(1)                        
d = u.unsqueeze(-1)
b.shape, c.shape, d.shape

(torch.Size([1, 3, 5]), torch.Size([3, 1, 5]), torch.Size([3, 5, 1]))

In [ ]:
# Flatten
x = torch.zeros(2, 3, 4)

flat = torch.flatten(x)
print(flat.shape)  # (2 * 3 * 4 = 24)

torch.Size([24])


In [ ]:
flat_two = torch.flatten(x, start_dim=1) # 2, (3*4 = 12) -> (2,12)
flat_two.shape

torch.Size([2, 12])

In [31]:
ff = torch.randn(1,2,3,4,5)
ff_flat = torch.flatten(ff, start_dim=1, end_dim=3) # 1, 2*3*4=24, 5)
ff_flat.shape

torch.Size([1, 24, 5])

In [35]:
x = torch.tensor([[1], [2], [3]])         # shape [3, 1]

# expand – broadcasting style (almost free)
y = x.expand(3, 4)  # y is a view. Memory still only stores the original 3 values.
print(y, y.shape)

# repeat – actually copies data
z = x.repeat(1, 4) # z owns its own storage with the values repeated.
print(z, z.shape)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4])


In [38]:
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]]) 
sm = x.sum()
print(sm, sm.shape) # tensor(21.)

s_dim0 = x.sum(dim=0) 
print(s_dim0)        
print(s_dim0.shape)  

# keepdim=True: Leaves the dimension as size 1
s_keep = x.sum(dim=0, keepdim=True)
print(s_keep)        
print(s_keep.shape)  

tensor(21.) torch.Size([])
tensor([5., 7., 9.])
torch.Size([3])
tensor([[5., 7., 9.]])
torch.Size([1, 3])


In [42]:
x = torch.tensor([[1., 2.], 
                  [3., 4.],
                  [8., 1.]])
# (3,2)
mn = x.mean(dim=1) # Row averages: tensor([1.5000, 3.5000])
print(mn, mn.shape)

mn_kpdim = x.mean(dim=1, keepdim=True)
print(mn_kpdim, mn_kpdim.shape)

tensor([1.5000, 3.5000, 4.5000]) torch.Size([3])
tensor([[1.5000],
        [3.5000],
        [4.5000]]) torch.Size([3, 1])


In [43]:
v = torch.tensor([3.0, 4.0])

# sqrt(3^2 + 4^2) = sqrt(9 + 16) = sqrt(25) = 5
print(torch.linalg.norm(v)) # tensor(5.)

# we can also do this along dimensions for batches of vectors
batch = torch.tensor([[3., 4.], [6., 8.]])
print(torch.linalg.norm(batch, dim=1)) 

tensor(5.)
tensor([ 5., 10.])


In [44]:
# Matmul
A = torch.tensor([[1, 2], 
                  [3, 4]])

B = torch.tensor([[5, 6],
                  [7, 8]])

# Element-wise (top-left is 1*5)
print(A * B) 
# [[ 5, 12],
#  [21, 32]]

# Matrix Multiplication (top-left is (1*5) + (2*7) = 19)
print(A @ B)
# [[19, 22],
#  [43, 50]]

tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])


#### Einsum rules

## The 3 Rules of Einsum

Every `einsum` string looks like this: `"inputs -> output"`.
(e.g., `"ij, jk -> ik"`)

1. **Letters are dimensions:** Each letter represents one axis of your tensor. A 2D matrix gets two letters (e.g., `ij`). A 3D tensor gets three (e.g., `bjk`).
2. **Repeating a letter across inputs means MULTIPLY:** If input A has a `j` and input B has a `j`, PyTorch will multiply the elements along that `j` dimension.
3. **Omitting a letter in the output means SUM (Squash):** If a letter appears in the inputs but is missing on the right side of the `->`, PyTorch will sum up all the values along that dimension.


In [ ]:
# einsum() is crazy
"""
Matrix Multiplication (The Classic)
What we have: A is ij, B is jk (Matrix A's columns j match Matrix B's rows j)
What we want: ik (Matrix A's rows, Matrix B's columns)
How it works: j is repeated, so we multiply along it. j is missing from the output, 
so we sum those products. (This is exactly how you calculate a dot product for every row/col pair in standard matrix math).
"""
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

print(torch.einsum('ij, jk -> ik', A, B))

tensor([[19, 22],
        [43, 50]])


In [ ]:
# When tensors does not need grad then we can safely do inplace ops with _

In [54]:
# Basically all the dimensions other than the dimension we are trying to concatanate has to be same

a = torch.randn(2, 3)
b = torch.randn(2, 5)
c = torch.randn(2, 4)

# a = torch.randn(2, 3, 4)
# b = torch.randn(2, 7, 4)
# c = torch.randn(2, 6, 4)

torch.cat([a, b, c], dim=1)   # shape: [2, 12]

tensor([[-1.3028, -0.8541,  1.6882,  1.0509, -1.1438,  0.9851,  0.6981,  0.7260,
         -0.1061, -1.4974,  0.8788, -0.7191],
        [-1.5650, -0.1092,  0.4059, -1.3294,  0.0262,  1.2405, -0.2964, -0.7906,
          0.2713,  0.9686,  0.2892, -0.3990]])

In [59]:
# all must be in same shape

a = torch.randn(3, 4)
b = torch.randn(3, 4)
c = torch.randn(3, 4)

print(torch.stack([a, b, c], dim=0))
print(torch.stack([a, b, c], dim=0).shape)
print(torch.stack([a, b, c], dim=2).shape)   

tensor([[[ 0.1789,  0.7805,  0.3929, -1.6264],
         [ 0.2211,  0.8317,  1.0220,  0.7796],
         [ 1.7725,  0.1933, -0.1040, -0.1940]],

        [[ 1.4736, -1.0287,  0.2276,  0.6702],
         [ 1.2279, -0.7882, -0.3830,  0.6116],
         [-1.5469,  0.3608,  1.5719,  0.3319]],

        [[ 2.3580, -0.0621, -0.2081, -1.1775],
         [ 2.2638,  0.2862,  0.1284,  1.0145],
         [ 1.1369, -0.8362, -0.8965,  0.9457]]])
torch.Size([3, 3, 4])
torch.Size([3, 4, 3])


In [ ]:
# ---------------------------------------------------------
# SETUP: Create one 3D tensor for both examples
# Shape: [Batch=2, Sequence=4, Features=6]
# ---------------------------------------------------------
x_3d = torch.arange(48).reshape(2, 4, 6)
print(f"Original tensor shape: {x_3d.shape}\n")

# ---------------------------------------------------------
# EXAMPLE 1: torch.split on dim=1 (Sequence)
# ---------------------------------------------------------
# We want to split the sequence (size 4) into chunks of size 3.
# This will leave a smaller leftover chunk at the end.
print("--- torch.split (Size-First) ---")
split_pieces = torch.split(x_3d, split_size_or_sections=3, dim=1)

for i, p in enumerate(split_pieces):
    print(f"Split Piece {i} shape: {p.shape}")

print("\n")

# ---------------------------------------------------------
# EXAMPLE 2: torch.chunk on dim=2 (Features)
# ---------------------------------------------------------
# We want exactly 3 equal chunks from the Features dimension (size 6).
# 6 / 3 = 2, so each chunk will have 2 features.
print("--- torch.chunk (Quantity-First) ---")
chunk_pieces = torch.chunk(x_3d, chunks=3, dim=2)

for i, p in enumerate(chunk_pieces):
    print(f"Chunk Piece {i} shape: {p.shape}")

Original tensor shape: torch.Size([2, 4, 6])

--- torch.split (Size-First) ---
Split Piece 0 shape: torch.Size([2, 3, 6])
Split Piece 1 shape: torch.Size([2, 1, 6])


--- torch.chunk (Quantity-First) ---
Chunk Piece 0 shape: torch.Size([2, 4, 2])
Chunk Piece 1 shape: torch.Size([2, 4, 2])
Chunk Piece 2 shape: torch.Size([2, 4, 2])


In [ ]:
matrix = torch.arange(12).reshape(3, 4)
print(f"Original shape: {matrix.shape}\n")

# Unbind along the rows (dim=0)
rows = torch.unbind(matrix, dim=0)
cols = torch.unbind(matrix, dim=1)
rows, cols

Original shape: torch.Size([3, 4])



((tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11])),
 (tensor([0, 4, 8]),
  tensor([1, 5, 9]),
  tensor([ 2,  6, 10]),
  tensor([ 3,  7, 11])))

In [64]:
# Shape: [Batch=2, Sequence=4, Features=6]
x_3d = torch.arange(48).reshape(2, 4, 6)
print(f"Original shape: {x_3d.shape}\n")

# Unbind along the Batch dimension (dim=0)
batch_items = torch.unbind(x_3d, dim=0)

print(f"Number of items in batch: {len(batch_items)}\n")
for i, item in enumerate(batch_items):
    print(f"Batch item {i} shape: {item.shape}")

Original shape: torch.Size([2, 4, 6])

Number of items in batch: 2

Batch item 0 shape: torch.Size([4, 6])
Batch item 1 shape: torch.Size([4, 6])
