In [1]:
import torch

In [2]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [3]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [7]:
id(points_t.storage()) == id(points.storage())

True

In [8]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

In [9]:
# So transposing is just changing the order of stride

In [26]:
a = torch.tensor([[[1,2,3,4], [1,2,3,6]],
                  [[0,2,1,4], [7,2,3,6]]])
a.transpose(0, 1)

tensor([[[1, 2, 3, 4],
         [0, 2, 1, 4]],

        [[1, 2, 3, 6],
         [7, 2, 3, 6]]])

In [12]:
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [13]:
points_t_cont = points_t.contiguous()
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [14]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### TENSOR to GPU

In [15]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [17]:
twice_points_gpu = points_gpu*2
twice_points_gpu

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')

In [27]:
a

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 6]],

        [[0, 2, 1, 4],
         [7, 2, 3, 6]]])

In [30]:
b = a.numpy()
b


array([[[1, 2, 3, 4],
        [1, 2, 3, 6]],

       [[0, 2, 1, 4],
        [7, 2, 3, 6]]])

In [31]:
a.layout

torch.strided

In [35]:
with open('./points.t', 'wb') as f:
    torch.save(points, f)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [36]:
with open('./points.t', 'rb') as f:
    loaded = torch.load(f)
loaded

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [37]:
import h5py

In [38]:
f = h5py.File('./ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [41]:
f = h5py.File('./ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[5., 3.],
       [2., 1.]], dtype=float32)

In [42]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [43]:
last_points

tensor([[5., 3.],
        [2., 1.]])