In [2]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [27]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]
                       ])
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [29]:
points.shape

torch.Size([3, 2])

In [30]:
points[1], points[1,1]

(tensor([5., 3.]), tensor(3.))

In [31]:
points[1:2, :]

tensor([[5., 3.]])

In [32]:
x = torch.tensor(
    [[1.0, 4.0, 8.0], [1.0, 4.0, 8.0], [1.0, 4.0, 8.0]], names=["row", "col"]
)

x

tensor([[1., 4., 8.],
        [1., 4., 8.],
        [1., 4., 8.]], names=('row', 'col'))

In [35]:
named_points = points.refine_names(...,"row", "column")
named_points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], names=('row', 'column'))

In [61]:
x = torch.rand(3)
print(x.shape)
x.unsqueeze(0).shape

torch.Size([3])


torch.Size([1, 3])

In [ ]:

a = torch.rand(3, 4, names=('H', 'W'))
b = torch.rand(1, 4, names=('H', 'W'))

# a = torch.rand(3, 4, names=('H', 'W')) Error thename does not match
# b = torch.rand(1, 4, names=('W', 'H'))

a + b
#this named thing is an experimental thing

tensor([[0.4072, 1.3791, 0.8392, 1.6113],
        [0.6573, 1.6680, 0.8240, 1.1801],
        [0.1558, 1.0468, 0.6894, 0.9438]], names=('H', 'W'))

In [ ]:
# Broadcasting is matching from right to left, if one of this is 1 then strech it up to n(other one)
# unsqueeze(d) is just adding a dimension at d index(between 2 dimension or front/back of 1 dimension)

In [ ]:
n = torch.tensor([[1,2,3,1], [4,5,6,9], [8,2,3,3]])
n.shape, n.sum(0)


(torch.Size([3, 4]), tensor([13,  9, 12, 13]))

In [67]:
# k = torch.tensor([2,2])
k = torch.tensor([2.0,2])
k.dtype

torch.float32

In [69]:
# Indexing
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
g = points.storage()
g[0]

4.0

In [70]:
t = torch.tensor([[1,2,3,4], [9,9,9,9]])
print(t)
t.zero_()
print(t)

tensor([[1, 2, 3, 4],
        [9, 9, 9, 9]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [71]:
t2 = t[1].clone()
t2

tensor([0, 0, 0, 0])

In [78]:
t3 = torch.tensor([[4,3,2,4], [3,4,0,0]]) 
p3 = t3[1,2]
print(p3.storage())
print(p3.storage_offset())
print(p3.stride())

 4
 3
 2
 4
 3
 4
 0
 0
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 8]
6
()


In [3]:
b = torch.arange(9)
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])